name: Deploy EC2 Instance on AWS

on:
  push:
    branches: 
     - main

env:
  STACK_NAME: ec-deploy    
  AWS_REGION: us-east-1 

jobs:
  Deploy-EC2-On-AWS:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }} 

      - name: Verify AWS Identity (Debug)
        run: aws sts get-caller-identity      

      - name: Deploy Cloud Formation
        run: |
          aws cloudformation deploy \
          --template-file EC2cft.yaml \
          --stack-name $STACK_NAME \
          --capabilities CAPABILITY_NAMED_IAM \
          --parameter-overrides file://EC2cft.json


